name: "Build"
description: "build the project"
on:
    push:
        branches:
          - "main"
          - "releases/**"
    pull_request:
        types: [opened, reopened]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository Content
              uses: actions/checkout@v2

            - name: Make
              run: make build