name: "Build"
description: "build the project"
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository Content
              uses: actions/checkout@v2

            - name: Make
              run: make build